### ISSUE TITLE
Configuration for OSM Liberty

### ISSUE THREAD

**Issue by abenrob** [klokantech/tileserver-gl#105]
Having trouble setting up for use with an osm-liberty formatted restyle.

Here is my Dir Structure:
```
└── data
    ├── config.json
    ├── grenoble_france.mbtiles
    ├── natural_earth_shaded_relief.raster.mbtiles
    └── styles
        └── liberty-light
            ├── liberty-light.json
            ├── sprites
            │   ├── osm-liberty@2x.json
            │   ├── osm-liberty@2x.png
            │   ├── osm-liberty.json
            │   └── osm-liberty.png
            └── svgs
                ├── aerialway-11.svg
                 ...
                └── zoo-15.svg
```
My config:
```
{
  "options": {
    "paths": {
      "root": "",
      "fonts": "styles",
      "sprites": "styles",
      "styles": "styles",
      "mbtiles": ""
    },
    "domains": [
      "localhost:8080",
      "127.0.0.1:8080"
    ],
    "formatQuality": {
      "jpeg": 80,
      "webp": 90,
      "pngQuantization": false,
      "png": 90
    },
    "maxSize": 2048
  },
  "styles": {
    "light": {
      "style": "liberty-light/liberty-light.json"
    }
  },
  "data": {
    "grenoble-vector": {
      "mbtiles": "grenoble_france.mbtiles"
    },
    "ne-shaded": {
      "mbtiles": "natural_earth_shaded_relief.raster.mbtiles"
    }
  }
}
```

And the sources part of _liberty-light.json_:
```
"sources": {
      "natural_earth_shaded_relief": {
         "maxzoom": 10,
         "tileSize": 256,
         "tiles": [
            "mbtiles://{ne-shaded}"
         ],
         "type": "raster"
      },
      "osm2vectortiles": {
         "type": "vector",
         "url": "mbtiles://{grenoble-vector}"
      }
   },
   "sprite": "sprites/liberty-light/osm-liberty",
   "glyphs": "https://orangemug.github.io/font-glyphs/glyphs/{fontstack}/{range}.pbf",
```

I am using docker, and starting from the _data_ dir using `docker run -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl`

These are the errors that are thrown:
```
Starting tileserver-gl v1.1.5
Using specified config file from config.json
Starting server
/usr/src/app/src/serve_style.js:19
    if (url.lastIndexOf('mbtiles:', 0) === 0) {
           ^

TypeError: Cannot read property 'lastIndexOf' of undefined
    at /usr/src/app/src/serve_style.js:19:12
    at Array.forEach (native)
    at module.exports (/usr/src/app/src/serve_style.js:16:34)
    at /usr/src/app/src/server.js:94:27
    at Array.forEach (native)
    at module.exports (/usr/src/app/src/server.js:86:36)
    at startServer (/usr/src/app/src/main.js:53:29)
    at /usr/src/app/src/main.js:165:12
    at FSReqWrap.oncomplete (fs.js:82:15)

```

When I use the style with the original data sources from osm-liberty in maputnik, the style displays as expected, so it seems to be related to the configuration.

This is an excellent project, and I'm very excited to use in production soon, but tripping up on the configuration.

Thanks for checking it out!

cc @lukasmartinelli in lukasmartinelli/osm-liberty#10

**Comment by petrsloup** [comment]
You can use the raster tiles the same way as vector tiles:
```json
      "natural_earth_shaded_relief": {
         "url": "mbtiles://{ne-shaded}",
         "type": "raster"
      },
      "osm2vectortiles": {
         "type": "vector",
         "url": "mbtiles://{grenoble-vector}"
      }
```

I also recommend updating to the latest version (`docker pull klokantech/tileserver-gl`). We've done many improvements and fixes to the handling of the sprite paths.
