### ISSUE TITLE
Use geojson file as multiple sources  causes error  in vector mode

### ISSUE THREAD

**Issue by JINCHUNGEUN** [klokantech/tileserver-gl#108]
i edited the style in the Maputnik. In the website editor  i add new sources,the source type  is geojson and data is from remote url..when i finished editing the style,i  exported the style json file..
before running the tileserver-gl docker , i only modified the sources of openmaptiles url  to local url. and run .when i  open as raster it works well,but when i open the in vector mode the error occurs
**part of style json file is as below**
``` 
 "sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "mbtiles://{v3}"
    },
    "places": {
      "type": "geojson",
      "data": "https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_50m_populated_places_simple.geojson"
    }
  },
  "glyphs": "{fontstack}/{range}.pbf",
```

ERROR:

```
GET /styles/ckstyle.json 500 10.040 ms - 890
TypeError: Cannot read property 'replace' of undefined
    at fixUrl (/usr/src/app/src/serve_style.js:74:17)
    at /usr/src/app/src/serve_style.js:81:20
    at Array.forEach (native)
    at /usr/src/app/src/serve_style.js:79:37
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:330:12)
```

**Comment by petrsloup** [comment]
Thanks for reporting. Yes, this was a bug, should be fixed now and will be part of the next release (or you can try the latest build).

**Comment by JINCHUNGEUN** [comment]
Thanks,i will try the latest build

**Comment by JINCHUNGEUN** [comment]
I try the latest build docker ,but another error occurs

Error:
```
XMLHttpRequest cannot load local://data/planet_z0_z14.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
```

**Comment by JINCHUNGEUN** [comment]
Thanks, it works
