### ISSUE TITLE
Problem with configuration / inspect vector. fixUrl

### ISSUE THREAD

**Issue by sweco-semtne** [klokantech/tileserver-gl#118]
Hi,
I tried to configure a style that uses local mbtiles, but seem to be doing something wrong. 
I'm running tileserver gl via docker. 

```
docker run -it -v $(pwd)/data:/data -p 8090:80 klokantech/tileserver-gl -c /data/tileserver.json
```

It picks up the configuration. I can preview the mbtiles inspect, but I must be doing something wrong with the style. 
I keep getting the error at the end.
The style references no local fonts, sprites etc. 
I get the same error even if I comment out the reference to the local mbtile files. 

The error occurs when I try to view the preview of the style. 

Any suggestions?

```
{
  "options": {
    "paths": {
      "root": "",
      "fonts": "",
      "sprites": "",
      "styles": "styles",
      "mbtiles": ""
    },
    "domains": [
      "localhost:8090",
      "127.0.0.1:8090"
    ],
    "formatQuality": {
      "jpeg": 80,
      "webp": 90,
      "pngQuantization": false,
      "png": 90
    },
    "maxSize": 2048,
    "pbfAlias": "pbf",
    "serveAllFonts": false
  },
  "styles": {
    "basic": {
      "style": "basemap.json",
      "serve_rendered": false,
      "tilejson": {
        "type": "overlay"
      }
    }
  },
  "data": {
    "points": {
      "mbtiles": "points.mbtiles"
    },
    "boxes": {
      "mbtiles": "boxes.mbtiles"
    }
  }
}
```

```javascript
TypeError: Cannot read property 'replace' of undefined
   at fixUrl (/usr/src/app/src/serve_style.js:74:17)
   at /usr/src/app/src/serve_style.js:81:20
   at Array.forEach (native)
   at /usr/src/app/src/serve_style.js:79:37
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
   at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
   at /usr/src/app/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:330:12)
   at next (/usr/src/app/node_modules/express/lib/router/index.js:271:10)
   at expressInit (/usr/src/app/node_modules/express/lib/middleware/init.js:33:5)
   at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:312:13)
   at /usr/src/app/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:330:12)
```

**Comment by petrsloup** [comment]
Update to the latest version (`docker pull klokantech/tileserver-gl`).
This was reported and solved in https://github.com/klokantech/tileserver-gl/issues/108.
