### ISSUE TITLE
debian 8 + node v4 + npm 2 as root => fail

### ISSUE THREAD

**Issue by devistar** [klokantech/tileserver-gl#163]
root@seattle-tileserver /srv/tileserver
 # npm install -g tileserver-gl
npm WARN deprecated mbtiles@0.9.0: This module has moved: please install @mapbox/mbtiles instead
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm WARN deprecated tiletype@0.1.0: This module is now under the @mapbox namespace: install @mapbox/tiletype instead
npm WARN deprecated sphericalmercator@1.0.5: This module is now under the @mapbox namespace: install @mapbox/sphericalmercator instead
npm WARN engine tiletype@0.1.0: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.8.3","npm":"2.15.11"})
 
> canvas@1.6.5 install /usr/lib/node_modules/tileserver-gl/node_modules/canvas
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.8.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/tileserver-gl/node_modules/canvas/.node-gyp"
./util/has_lib.sh: 31: ./util/has_lib.sh: pkg-config: not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/tileserver-gl/node_modules/canvas
gyp ERR! node -v v4.8.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
 
> sqlite3@3.1.8 install /usr/lib/node_modules/tileserver-gl/node_modules/mbtiles/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/usr/lib/node_modules/tileserver-gl/node_modules/mbtiles/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node" is installed via remote
 
> node-pngquant-native@1.0.4 install /usr/lib/node_modules/tileserver-gl/node_modules/node-pngquant-native
> echo "Hello, World"

Hello, World
 
> @mapbox/mapbox-gl-native@3.4.4 preinstall /usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native
> npm install node-pre-gyp

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-pre-gyp"
npm ERR! node v4.8.3
npm ERR! npm  v2.15.11
npm ERR! path /root/.npm/node-pre-gyp/0.6.34/package
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/root/.npm/node-pre-gyp/0.6.34/package'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/root/.npm/node-pre-gyp/0.6.34/package']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/root/.npm/node-pre-gyp/0.6.34/package' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native/npm-debug.log
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
/
> sharp@0.17.3 install /usr/lib/node_modules/tileserver-gl/node_modules/sharp
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.8.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/tileserver-gl/node_modules/sharp/.node-gyp"
make: Entering directory '/usr/lib/node_modules/tileserver-gl/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  COPY Release/sharp.node
  TOUCH Release/obj.target/win_copy_dlls.stamp
make: Leaving directory '/usr/lib/node_modules/tileserver-gl/node_modules/sharp/build'
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "tileserver-gl"
npm ERR! node v4.8.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/tileserver/npm-debug.log

**Comment by huehnerhose** [comment]
Got the same errors with FreeBSD 10, node7.10 and node6.10.3, npm  in various versions.

**Comment by peldhose** [comment]
hi , 
can you try with their Dockerfile commands in a debian stretch os ? Mine last worked by executing exact commands from their dockerfile in a Debian stretch OS. try

**Comment by tschwaerzl** [comment]
Same with Ubuntu 16.04.3 LTS

`root@maps ~ # npm install -g tileserver-gl
npm WARN engine tileserver-gl@2.2.0: wanted: {"node":">=6 <7"} (current: {"node":"4.8.4","npm":"2.15.11"})

> canvas@1.6.6 install /usr/lib/node_modules/tileserver-gl/node_modules/canvas
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.8.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/tileserver-gl/node_modules/canvas/.node-gyp"
./util/has_lib.sh: 31: ./util/has_lib.sh: pkg-config: not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.8.0-58-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/tileserver-gl/node_modules/canvas
gyp ERR! node -v v4.8.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> sharp@0.18.2 install /usr/lib/node_modules/tileserver-gl/node_modules/sharp
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.8.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/tileserver-gl/node_modules/sharp/.node-gyp"
make: Entering directory '/usr/lib/node_modules/tileserver-gl/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  COPY Release/sharp.node
  TOUCH Release/obj.target/win_copy_dlls.stamp
make: Leaving directory '/usr/lib/node_modules/tileserver-gl/node_modules/sharp/build'

> sqlite3@3.1.11 install /usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mbtiles/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mbtiles/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node" is installed via remote

> @mapbox/mapbox-gl-native@3.5.4 preinstall /usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native
> npm install node-pre-gyp

npm ERR! Linux 4.8.0-58-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-pre-gyp"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! path /root/.npm/node-pre-gyp/0.6.37/package
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/root/.npm/node-pre-gyp/0.6.37/package'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/root/.npm/node-pre-gyp/0.6.37/package']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/root/.npm/node-pre-gyp/0.6.37/package' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native/npm-debug.log

> node-pngquant-native@1.0.5 install /usr/lib/node_modules/tileserver-gl/node_modules/node-pngquant-native
> echo "Hello, World"

Hello, World
npm ERR! Linux 4.8.0-58-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "tileserver-gl"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log`

**Comment by asecondwill** [comment]
same kind of problems trying to install on debian 9 and ubuntu 16.

**Comment by lifeofguenter** [comment]
For this to work you will have to install some packages/dependencies first:

```bash
$ sudo apt install pkg-config libcairo2-dev libjpeg62-turbo-dev make gcc
$ sudo npm install -g tileserver-gl
```
