### ISSUE TITLE
running docker tileserver-gl on windows with custom mbtile

### ISSUE THREAD

**Issue by anees042** [klokantech/tileserver-gl#175]
I am getting the following error; can some one help please?

i was following documentation http://tileserver.readthedocs.io/en/latest/installation.html#docker

```docker run ... klokantech/tileserver-gl my-tiles.mbtiles – explicitly specify which mbtiles to use (if you have more in the folder)```

```

E:\git\gis>docker run -it -v //e/git/gis -p 8080:80 klokantech/tileserver-gl E://git/gis/data/united_arab_emirates.mbtiles
Starting tileserver-gl v1.7.0
Automatically creating config file for E://git/gis/data/united_arab_emirates.mbtiles
fs.js:844
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/data/E:/git/gis/data/united_arab_emirates.mbtiles'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at startWithMBTiles (/usr/src/app/src/main.js:71:25)
    at /usr/src/app/src/main.js:201:14
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by klokan** [comment]
For the united_arab_emirates.mbtiles file you must use a relative path to the directory `-v` volume binding - and your volume binding must map to internal "/data" folder!

This may do it:
```
docker run -it -v //e/git/gis/data:/data -p 8080:80 klokantech/tileserver-gl united_arab_emirates.mbtiles
```
