### ISSUE TITLE
Error on http://localhost:8080/ call

### ISSUE THREAD

**Issue by gmuc** [klokantech/tileserver-gl#237]
I started tileserver-gl
docker run --rm -it -v $(pwd):/data -p 8080:80 klokantech/tileserver-gl

Now I open the wizzard on http://localhost:8080/ and got "Internal Server Error"  What's the reason?

```
GET / 500 148 - 15.298 ms
TypeError: Cannot create property 'name' on string ''
    at /usr/src/app/src/server.js:278:18
    at Array.forEach (native)
    at /usr/src/app/src/server.js:276:25
    at /usr/src/app/src/server.js:257:20
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/node_modules/express/lib/application.js:233:9
```

on klokantech/openmaptiles-server the wizzard work correct on  http://localhost:8080
`docker run --rm -it -v $(pwd):/data -p 8080:80 klokantech/openmaptiles-server `

BUT if I use a Dockerfile:

```
FROM klokantech/tileserver-gl:v2.2.0
ADD . /
```

docker-compose.yml

```
version: '2.1'
services:
  tileserver:
    build: tileserver
    ports:
    - "8080:80"
```

klokantech/tileserver-gl work fine. I call http://localhost:8080/ and get the wizzard.

What the difference between start via docker on cmdline or start via docker-compose?

I use Mac OS 10.12.6.

**Comment by gmuc** [comment]
Now it work! Any new bugfix?
