### ISSUE TITLE
Unable to start tileserver-gl

### ISSUE THREAD

**Issue by aaronakku** [klokantech/tileserver-gl#261]
I have been trying install tileserver-gl  using npm and faced errors on installing it in _node version(v6.11.3) and npm version(3.10.10),_ and on trying to start tileserver with mbtiles is receiving the Error as follows
**bash: tileserver-gl: command not found**
and on running the first command in the above mentioned versions,i happen to get the following errors
**npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.**

I tried using npm install && npm link and got couple of errors
**node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v3.5.4/node-v59-linux-x64-Release.tar.gz**
 on trying **wget  https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v3.5.4/node-v59-linux-x64-Release.tar.gz**
This is what i get..
**HTTP request sent, awaiting response... 403 Forbidden
2018-03-06 21:27:48 ERROR 403: Forbidden.**

**Comment by Rajavelu** [comment]
I met following err:
> tileserver-gl 

Starting tileserver-gl v2.3.1
No MBTiles specified, using india.mbtiles
Automatically creating config file for india.mbtiles
Run with --verbose to see the config file here.
module.js:471
    throw err;
    ^

Error: Cannot find module '../build/Release/sharp.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/tileserver-gl/node_modules/sharp/lib/constructor.js:9:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by aaronakku** [comment]
I happened to get it right!
Installed Docker and used it to set up the tileserver.

Thank You 
:)
