### ISSUE TITLE
Error while starting tileserver-gl

### ISSUE THREAD

**Issue by Rajavelu** [klokantech/tileserver-gl#264]
>tileserver-gl

Starting tileserver-gl v2.3.1
No MBTiles specified, using india.mbtiles
Automatically creating config file for india.mbtiles
Run with --verbose to see the config file here.
module.js:471
throw err;
^

Error: Cannot find module '../build/Release/sharp.node'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (/usr/lib/node_modules/tileserver-gl/node_modules/sharp/lib/constructor.js:9:15)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

**Comment by klokan** [comment]
Use docker, please.

Or do installation on your system properly. Missing module on your computer is not an issue of the code in this repository.
