### ISSUE TITLE
EACCES: permission denied, scandir '/data'

### ISSUE THREAD

**Issue by Forensik-IT** [klokantech/tileserver-gl#315]
Hi!

I'm trying to setup the TileServer with docker.
I downloaded this mbtile : https://openmaptiles.com/downloads/tileset/osm/europe/germany/ 
"osm-2017-07-03-v3.6.1-europe_germany.mbtiles"

I placed it in the following path:
/home/user/Documents/.../tileserver

after i navigated to this folder I downloaded the dockerimage from dockerhub with the following command:

`sudo docker pull klokantech/tileserver-gl:v2.4.0`

When i want to start it with this command:

`sudo docker run --rm - it - v $(pwd):/data -p 8080:80 klokantech/tileserver-gl`

I get following error Message:

```
Waiting 3 seconds for xvfb to start...
Starting tileserver-gl v2.4.0
fs.js:961
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: EACCES: permission denied, scandir '/data'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at /usr/src/app/src/main.js:181:22
    at FSReqWrap.oncomplete (fs.js:123:15)

```

After i have read through some issues here in Github i realized that i have to put the *.mbtile in a directory named /data within the directory I terminate the "docker run"-command. 
But again I got the same Error-Message.
I also used the following command to ensure that the User-Group is defined right:

`sudo chown -R user /home/user/Documents/.../tileserver`

I would be very thankful if you could share your ideas for the solution of this problem.

**Comment by jacktmcginnis** [comment]
@Forensik-IT Were you able to fix this issue? I'm running into similar problems

**Comment by sebastianknopf** [comment]
Is there an update yet? I'm facing the same issue and don't know where to enter.
