### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by lucasvw** [klokantech/tileserver-gl#90]
Hi guys,

I am trying to setup the tileserver-gl. Unfortunately I have no access to docker on the VM (Ubuntu 16.04), so I have to install over npm. I am having some problems during

    sudo npm install tileserver-gl -g --unsafe-perm

Namely:

```
26708 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "tileserver-gl" "-g" "--unsafe-perm"
26709 error node v6.9.2
26710 error npm  v3.10.9
26711 error path /usr/lib/node_modules/.staging/abbrev-4786dede
26712 error code ENOENT
26713 error errno -2
26714 error syscall rename
26715 error enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/abbrev-4786dede' -> '/usr/lib/node_modules/tileserver-gl/node_modules/abbrev'
26716 error enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/abbrev-4786dede' -> '/usr/lib/node_modules/tileserver-gl/node_modules/abbrev'
26716 error enoent This is most likely not a problem with npm itself
26716 error enoent and is related to npm not being able to find a file.
26717 verbose exit [ -2, true ]
```

When I am trying to install without the -g flag, I see that "abbrev" package is being installed under node_modules. Unfortunately, without the -g flag there are some other problems, it can't find the package.json at some point:

```
30082 warn enoent ENOENT: no such file or directory, open '/home/tileServer/package.json'
30083 verbose enoent ENOENT: no such file or directory, open '/home/tileServer/package.json'
30083 verbose enoent This is most likely not a problem with npm itself
30083 verbose enoent and is related to npm not being able to find a file.
30084 warn tileServer No description
30085 verbose If you need help, you may report this error at:
30085 verbose     <https://github.com/npm/npm/issues>
30086 warn tileServer No repository field.
30087 verbose If you need help, you may report this error at:
30087 verbose     <https://github.com/npm/npm/issues>
30088 warn tileServer No README data
30089 verbose If you need help, you may report this error at:
30089 verbose     <https://github.com/npm/npm/issues>
30090 warn tileServer No license field.
30091 verbose If you need help, you may report this error at:
30091 verbose     <https://github.com/npm/npm/issues>
30092 verbose stack Error: canvas@1.5.0 install: `node-gyp rebuild`
30092 verbose stack Exit status 1
30092 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
30092 verbose stack     at emitTwo (events.js:106:13)
30092 verbose stack     at EventEmitter.emit (events.js:191:7)
30092 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
30092 verbose stack     at emitTwo (events.js:106:13)
30092 verbose stack     at ChildProcess.emit (events.js:191:7)
30092 verbose stack     at maybeClose (internal/child_process.js:877:16)
30092 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
30093 verbose pkgid canvas@1.5.0
30094 verbose cwd /home/tileServer
30095 error Linux 4.4.0-042stab120.6
30096 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "tileserver-gl" "--unsafe-perm"
30097 error node v6.9.2
30098 error npm  v3.10.9
30099 error code ELIFECYCLE
30100 error canvas@1.5.0 install: `node-gyp rebuild`
30100 error Exit status 1
30101 error Failed at the canvas@1.5.0 install script 'node-gyp rebuild'.
30101 error Make sure you have the latest version of node.js and npm installed.
30101 error If you do, this is most likely a problem with the canvas package,
30101 error not with npm itself.
30101 error Tell the author that this fails on your system:
30101 error     node-gyp rebuild
30101 error You can get information on how to open an issue for this project with:
30101 error     npm bugs canvas
30101 error Or if that isn't available, you can get their info via:
30101 error     npm owner ls canvas
30101 error There is likely additional logging output above.
```

Any ideas ?

**Comment by lucasvw** [comment]
Okay, made it work with the comment of procogent: https://github.com/klokantech/tileserver-gl/issues/68


```
sudo apt-get install -y software-properties-common protobuf-compiler pkg-config libcairo2-dev libjpeg-dev libgif-dev git libgl1-mesa-glx build-essential g++ curl

curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs xvfb

sudo mkdir /var/cache/npm
sudo npm config set cache /var/cache/npm --global

cd /tmp
git clone https://github.com/klokantech/tileserver-gl.git
cd tileserver-gl/

sudo npm install -g --unsafe-perm
```

**Comment by petrsloup** [comment]
Thanks, I added a paragraph to the documentation to make this more clear.
